OrdererOrgs:
  - Name: orderer
    Domain: pi.elisabeth.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: fcefyn
    Domain: fcefyn.pi.elisabeth.com
    #EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: famaf
    Domain: famaf.pi.elisabeth.com
    #EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: fcq
    Domain: fcq.pi.elisabeth.com
    #EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
